#
# ███    ███ ███    ███  ██████   ██████  ██████  ██████  ███████
# ████  ████ ████  ████ ██    ██ ██      ██    ██ ██   ██ ██
# ██ ████ ██ ██ ████ ██ ██    ██ ██      ██    ██ ██████  █████
# ██  ██  ██ ██  ██  ██ ██    ██ ██      ██    ██ ██   ██ ██
# ██      ██ ██      ██  ██████   ██████  ██████  ██   ██ ███████
#
# a Spigot Plugin by Team Requiem

# DO NOT TOUCH
config-version: 7

# Auto-Save feature automatically saves playerdata
# (class, level, etc.) and guild data
# (guild names, members, etc.) at a set interval.
auto-save:
    enabled: true
    interval: 1800 # In seconds (1800 = 30 minutes)

# MySQL Support
mysql:
    enabled: false
    host: 145.239.88.2
    port: 3306
    database: 's2877_mine'
    user: 'u2877_aPlfMrGwNF'
    pass: 'dNtJvKo8BQ.Vf0VQ@u^1!2uY'
    properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
    # Will verbose to the console whenever
    # data is saved/loaded from the SQL database.
    debug: false

# The default values for all playerdata
# All new players will start with these values
default-playerdata:
    level: 1
    class-points: 1
    skill-points: 10
    attribute-points: 2
    attribute-realloc-points: 0

# The list of all conditions which must be met for the
# BLOCK REGEN and BLOCK RESTRICTIONS to apply. Set to
# 'custom-mine-conditions: []' to disable custom mining entirely.
custom-mine-conditions: []

#
# custom-mine-conditions:
# - 'world{name="__global__"}'
#
# ^ will enable custom mining server wide

# Set to true to prevent vanilla blocks from being
# broken when custom mining conditions are met
protect-custom-mine: false

should-cobblestone-generators-give-exp: false

loot-chests:

    # Time in seconds it takes for a loot chest to
    # expire after it was spawned. 600 is 10 minutes.
    chest-expire-time: 600
    
    # Interval in seconds before the same player
    # spawns two loot chests in ANY region.
    player-cooldown: 600

# Settings for the default action bar
action-bar:

    # Whether or not to use the default action bar.
    # (This doesn't change any other action bars provided by MMOCore.)
    enabled: false
    
    # The decimal format for stats (not including stat formats in stats.yml)
    decimal: "0.#"
    
    # The amount of miliseconds the bar will be faded
    #out when displaying other action bars.
    time-out: 0
    
    # The amount of ticks before updating the info
    ticks-to-update: 5
    
    # How to display the data.
    format: "&c❤ {health}/{max_health} &f| {mana_icon} {mana}/{max_mana} &f| &7⛨ {armor} &f| &2⌛ {stamina}/{max_stamina} &f| &d⇵ {stellium}/{max_stellium}" 

party:

    # Edit party buffs here. You may
    # add as many stats as you want.
    buff:
        health-regeneration: 1
        additional-experience: 1
    
    # Prefix you need to put in the chat
    # to talk in the party chat.
    chat-prefix: '@'

    # The max players that can be in
    # any given party. Between 2-8.
    max-players: 8    

# Redirects vanilla experience obtained to MMOCore
# class experience. You can define the % of the vanilla
# experience that is being transfered as MMOCore exp.
# Requires a SERVER reload when changed.
vanilla-exp-redirection:
    enabled: false
    ratio: 0.8

# Enable this open to override vanilla EXP and display
# level progress on the vanilla experience bar.
# Requires a SERVER reload when changed.
override-vanilla-exp: false

# If main class experience holograms should be displayed
# whenever a player earns main class exp
display-main-class-exp-holograms: true 

# Requires a SERVER reload when changed.
death-exp-loss:
    enabled: true
    
    # Percentage of current EXP you lose when dying.
    percent: 10

# Put the "value" of the action you want.
# If the value is invalid or empty it will
# default to the vanilla minecraft action.
# spell_cast
# Enters the default spell casting mode
# hotbar_swap
# Players can swap their hotbar with the 9 inventory slots
# right above it by pressing [swap items] while crouching.
# THis allows players to have two combat item sets.
# - vanilla
# The default F action, swapping main hand and offhand.
swap-keybind:
    normal: spell_cast
    sneaking: hotbar_swap

# Set this to true to allow players
# in creative mode to enter casting mode
can-creative-cast: true

# Use this option if you're having issue with Anvil GUIs.
# This replaces anvil inputs by chat inputs.
use-chat-input: true

# Prevents mobs spawned from spawners from giving XP points.
prevent-spawner-xp: true

# Timer for combat log to expire (in seconds)
combat-log:
    timer: 10

# Change this to the name of the color you want for
# the different resource bar placeholders
resource-bar-colors:
    stamina-whole: 'GREEN'
    stamina-half: 'DARK_GREEN'
    stamina-empty: 'WHITE'

# Whether or not the admin commands should display
# the result of the command when ran.
# For Example: "Players Level is now 10."
# Accepted Values:
# true - Always verbose
# player - Only verbose when ran from a player
# console - Only verbose when ran from console
# false - Never verbose
command-verbose:
    attribute: true
    class: true
    experience: true
    level: true
    nocd: true
    points: true
    reset: true
    resource: false