# Display options, it's not displayed anywhere so pointless.
# Just need the name for reference and PAPI placeholders.
display:
    name: '§3§lЧеловек'

# This is the default class which players have when
# joining the server. They can level it up, but they
# cannot choose this class again after changing their
# class because it is not displayed in /class
options:
    default: true
    display: false
    
    # Only regens when out of combat
    off-combat-health-regen: false
    off-combat-mana-regen: false

# Must match an existing exp curve filename from the 'expcurves' folder
exp-curve: levels2

triggers:
    class-chosen:
    - 'command{format="lp user %player% meta addprefix 2 &fЧеловек"}'        

# Experience sources for main class experience.
main-exp-sources:
- 'killmob{type=ZOMBIE;amount=1-3}'