display:
    name: '§9Маг'
    attribute-lore:
    - '&8&oСпециальзация'  
    - '&2 * &7Нанесение урона по области'         
    - '&2 * &7Навыки направлены на урон'    
    - '&a + &7Большой объём маны'    
    - '&a + &7Высокое восстановление маны'    
    - '&6 + &7Восстановление маны во время боя'    
    - '&6 + &7Нету перезарядки у атакующих навыков'     
    - '&8&oСила'
    - '&7  Объём здоровье: &c20 &7(+&c0.5&7)'    
    - '&7  Регенерация здоровья: &c0.04 &7(+&c0.02&7)'
    - '&8&oЛовкость'
    - '&7  Урон дальнего оружия: &a11% &7(+&a1%&7)'
    - '&8&oИнтеллект'
    - '&7  Магический урон: &920% &7(+&92%&7)'    
    - '&7  Объём маны: &950 &7(+&910&7)'
    - '&7  Восстановления маны: &90.2 &7(+&90.05&7)'
    - ''
    item: ENDER_EYE

cast-particle:
    particle: CRIT
    
# Must match an existing exp curve filename from the 'expcurves' folder
exp-curve: levels2

# Players cannot go further than Lvl 100
max-level: 30

triggers:
    class-chosen:
    - 'command{format="lp user %player% meta setprefix 3 &9Маг"}'
    level-up:
    - 'command{format="mmocore admin attribute-points give %player% 2"}'
    level-up-5:      
    - 'command{format="mmocore admin skill-points give %player% 5"}'
    level-up-10:      
    - 'command{format="mmocore admin skill-points give %player% 5"}'
    level-up-15:      
    - 'command{format="mmocore admin skill-points give %player% 5"}'
    level-up-20:      
    - 'command{format="mmocore admin skill-points give %player% 5"}'
    level-up-25:      
    - 'command{format="mmocore admin skill-points give %player% 5"}'
    level-up-30:      
    - 'command{format="mmocore admin skill-points give %player% 5"}'
    - 'command{format="lp user %player% meta setprefix 4 &9Архимаг"}'

# This is the default mana display options, however it is not mandatory
# to have it in your class config file. Other classes do not have this
# section and therefore have the default mana display options.
#
# 'char' is the character used to generate the mana bar as a message
# 'color' are also the colors used to generate the mana bar
# 'icon' is the icon display on the player action bar
# 'name' is basically displayed everywhere
mana:
    char: ■
    icon: '&9⭐'
    color:
        full: AQUA
        half: BLUE
        empty: WHITE
    name: 'Маны'

options:
    off-combat-health-regen: true
    off-combat-mana-regen: false
    off-combat-stamina-regen: false
    off-combat-stellium-regen: false

attributes:
    max-health:
        base: 22.0
        per-level: 2
    health-regeneration:
        base: 0.12
        per-level: 0.02       
    projectile-damage:
        base: 11
        per-level: 1    
    magic-damage:
        base: 22
        per-level: 2        
    max-mana:
        base: 110
        per-level: 10
    mana-regeneration:
        base: 1.1
        per-level: 0.1        

skills:
    FIRE_STORM:
        level: 5
        max-level: 11
    ManaShield:
        level: 10
        max-level: 11 
    Fireball2:
        level: 15
        max-level: 11 
    WARP:
        level: 20
        max-level: 11 
    Thunderball:
        level: 25
        max-level: 1   
        

# Experience sources for main class experience.
main-exp-sources:
- 'killmob{type=ENDER-DRAGON;amount=50-100}'
- 'killmob{type=SPIDER;amount=1-3}'
- 'killmob{type=CREEPER;amount=3-5}'
- 'killmob{type=STRAY;amount=2-3}'
- 'killmob{type=SKELETON;amount=2-3}'
- 'killmythicmob{type=SpiderScout;amount=10-25}'
- 'killmythicmob{type=PoisonSpider;amount=100-150}'
- 'killmythicmob{type=SkeletonArcher;amount=10-15}'
- 'killmythicmob{type=SkeletonSwordsman;amount=10-15}'
- 'killmythicmob{type=SkeletonKnight;amount=100-150}'
- 'killmythicmob{type=ZombieSwordsman;amount=10-15}'
- 'killmythicmob{type=ZombieCommander;amount=100-150}'
- 'killmythicmob{type=LowLich;amount=500-1000}'
- 'killmythicmob{type=IceSpirit;amount=100-200}'
- 'killmythicmob{type=IceGuard;amount=25-60}'
- 'killmythicmob{type=ZombiePirate;amount=15-20}'
- 'killmythicmob{type=ZombieCommanderPirate;amount=250-300}'
- 'killmythicmob{type=AngryGreenSludge;amount=80-100}'
- 'killmob{type=HUSK;amount=1-2}'
- 'killmob{type=DROWNED;amount=1-2}'
- 'killmob{type=ZOMBIE;amount=1-2}'
- 'killmythicmob{type=ZombieSwordsman;amount=10-15}'
- 'killmob{type=WITCH;amount=6-8}'
- 'killmob{type=GHAST;amount=4-6}'
- 'killmob{type=PILLAGER;amount=2-4}'
- 'killmob{type=ILLUSIONER;amount=3-4}'
- 'killmob{type=VINDICATOR;amount=2-4}'
- 'killmob{type=RAVAGER;amount=5-6}'
- 'killmob{type=GUARDIAN;amount=3-4}'
- 'killmob{type=ELDER-GUARDIAN;amount=20-25}'
- 'killmob{type=MAGMA-CUBE;amount=1-2}'